-- Log dos comandos utilizados para criar a tabela

CREATE TABLE NEWSLETTER(
	IDEMAIL INT PRIMARY KEY AUTO_INCREMENT,
	EMAIL VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE DATA (
	IDDATA INT PRIMARY KEY AUTO_INCREMENT,
	DATA CHAR(10) NOT NULL UNIQUE
);

CREATE TABLE HORARIO (
	IDHORARIO INT PRIMARY KEY AUTO_INCREMENT,
	HORARIO CHAR(5) NOT NULL UNIQUE
);

INSERT INTO HORARIO VALUES(NULL,'0800');
INSERT INTO HORARIO VALUES(NULL,'0830');
INSERT INTO HORARIO VALUES(NULL,'0900');
INSERT INTO HORARIO VALUES(NULL,'0930');
INSERT INTO HORARIO VALUES(NULL,'1000');
INSERT INTO HORARIO VALUES(NULL,'1030');
INSERT INTO HORARIO VALUES(NULL,'1100');
INSERT INTO HORARIO VALUES(NULL,'1130');
INSERT INTO HORARIO VALUES(NULL,'1200');
INSERT INTO HORARIO VALUES(NULL,'1230');
INSERT INTO HORARIO VALUES(NULL,'1300');
INSERT INTO HORARIO VALUES(NULL,'1330');
INSERT INTO HORARIO VALUES(NULL,'1400');
INSERT INTO HORARIO VALUES(NULL,'1430');
INSERT INTO HORARIO VALUES(NULL,'1500');
INSERT INTO HORARIO VALUES(NULL,'1530');
INSERT INTO HORARIO VALUES(NULL,'1600');
INSERT INTO HORARIO VALUES(NULL,'1630');
INSERT INTO HORARIO VALUES(NULL,'1700');
INSERT INTO HORARIO VALUES(NULL,'1730');

CREATE TABLE DATA_HORARIO(
	ID_DATA INT,
	ID_HORARIO INT,
	PRIMARY KEY(ID_DATA,ID_HORARIO)
);

ALTER TABLE DATA_HORARIO
ADD CONSTRAINT FK_DATA
FOREIGN KEY(ID_DATA)
REFERENCES DATA(IDDATA);

ALTER TABLE DATA_HORARIO
ADD CONSTRAINT FK_HORARIO
FOREIGN KEY(ID_HORARIO)
REFERENCES HORARIO(IDHORARIO);

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
	SOBRENOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	TELEFONE VARCHAR(11) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL
	ID_CIDADE INT,
	ID_BAIRRO INT
);

CREATE TABLE DATA_CLIENTE(
	ID_DATA INT,
	ID_CLIENTE INT,
	PRIMARY KEY(ID_DATA,ID_CLIENTE)
);

ALTER TABLE DATA_CLIENTE
ADD CONSTRAINT FK_DATA_CLIENTE
FOREIGN KEY(ID_DATA)
REFERENCES DATA(IDDATA);

ALTER TABLE DATA_CLIENTE
ADD CONSTRAINT FK_CLIENTE_DATA
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

CREATE TABLE CIDADE(
	IDCIDADE INT PRIMARY KEY AUTO_INCREMENT,
    CIDADE VARCHAR(50) NOT NULL UNIQUE
);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CIDADE
FOREIGN KEY(ID_CIDADE)
REFERENCES CIDADE(IDCIDADE);

CREATE TABLE BAIRRO(
	IDBAIRRO INT PRIMARY KEY AUTO_INCREMENT,
    BAIRRO VARCHAR(50) NOT NULL UNIQUE
);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_BAIRRO
FOREIGN KEY(ID_BAIRRO)
REFERENCES BAIRRO(IDBAIRRO);